# pyworkplace: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: docker-compose up
version: '3'
services:

  app:
    ports:
      - "80:8000"
    restart: always
    image: python:3.6.1
    environment: &environment
      - SECRET_KEY=u@g-x3m3_-npvkr*pw*1&^8bw0#!l&(3j3oqe_+=vsp26o74i1
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/usr/src
    env_file:
      - .env
