# pyworkplace: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up
version: '3'
services:

  app:
    environment: &environment
      - SECRET_KEY=u@g-x3m3_-npvkr*pw*1&^8bw0#!l&(3j3oqe_+=vsp26o74i1
    build:
      context: .
      dockerfile: docker/app-test/Dockerfile
